# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: http://image18.poco.cn/mypoco/myphoto/20161225/00/18449013420161225000913055.jpg?500x451_120

# avatar: http://image18.poco.cn/mypoco/myphoto/20161224/23/18449013420161224234436077.jpg?2048x1280_120
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: http://image18.poco.cn/mypoco/myphoto/20161225/00/18449013420161225000913055.jpg?500x451_120

# disqus
#disqus_shortname: drakeleung

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# nav #
nav:
  home: .
  archive: archives
  category: categories
  about: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  # github: https://github.com/GallenHu
  # weibo: http://weibo.com/10010800
  mail: mailto:chc199310@gmail.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content:

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>
